name: Check runners OS

on:
  push:
    branches:
      - test

permissions:
  contents: read

jobs:
  report:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Print runner OS
        run: echo "Running on $RUNNER_OS"