name: Create issue

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string
    
    outputs:
      issue-num: 
        description: 'Created issue number'
        value: ${{ jobs.create.outputs.issue-num }}

permissions:
  issues: write 

jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      issue-num: ${{ steps.create.outputs.issue_number }}
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq
      
      - name: Create GitHub issue
        id: create
        run: |
          RESPONSE=$(curl --silent --fail -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues \
          -d "$(jq -n --arg title "${{ inputs.title }}" --arg body "${{ inputs.body }}" '(title: $title, body: $body)')")

          echo "API response: $RESPONSE"

          ISSUE_NUMBER=$(echo "$RESPONSE" | jq -r '.number')

          if [[ "ISSUE_NUMBER" == "null" || -z "$ISSUE_NUMBER" ]]; then
            echo "❌ Failed to create issue or parse issue number"
            exit 1
          fi

          echo "✅ Issue created with number: $ISSUE_NUMBER"
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT