name: Create demo issue 3

on:
  push:

jobs:
  create-new-issue:
    strategy:
      matrix:
        prod: [prod1, prod2]
        level: [dev, stage, prod]

    runs-on: ubuntu-latest
    steps:
      - name: Create issue using reusable workflow
        uses: yooodleee/simple-go-proj/.github/workflow/create-issue.yml@v1
        with:
          title: "${{ matrix.prod }} issue"
          body: "Update for ${{ matrix.level }}"
      
      - name: Output context (optional debug)
        run: |
          echo "Matrix: ${{ matrix.prod }}"
          echo "Level: ${{ matrix.level }}"