name: Create issue

on:
  workflow_call:
    inputs:
      title:
        required: true
        type: string
      body:
        required: true
        type: string
    
    outputs:
      issue-num: 
        description: 'Created issue number'
        value: ${{ jobs.create.outputs.issue-num }}

jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      issue-num: ${{ steps.create.outputs.issue_number }}
    steps:
      - id: create
        run: |
          ISSUE_NUMBER=123 
          echo "issue_number=$ISSUE_NUMBER" >> $GITHUB_OUTPUT