name: Go Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set cache-name env var
        run: echo "cache-name=go-cache" >> $GITHUB_ENV

      - name: Cache Go modules
        uses: actions/cache@v3
        env:
          cache-name: go-cache
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build Go binary
        run: |
          mkdir -p dist
          go build -o dist/app main.go

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-binary
          path: dist/app