name: Notify on New Issue

on:
  issues:
    types: [opened, edited, closed]
  pull_request:
    types: [opened, closed]
  push:
    branches:
      - main
      - 'rel/v*'
    tags:
      - v1.*
      - beta

jobs:
  notify-for-issue: 
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notifiaction
        run: |
          payload="{
            \"text\": "\🔔 *Issue Event: ${{ github.event.action }}*\n
            *Title:* ${{ github.event.issue.title }}\n
            *Body:* ${{ github.event.issue.body || 'No content' }}\n
            *Author:* ${{ github.event.issue.user.login }}\n
            *URL:* ${{ github.event.issue.html_url }}\"
          }"

          echo "$payload"

          curl -X POST -H 'Content-type: application/json' \
            --data "$payload" \
            ${{ secrets.SLACK_WEBHOOK_URL }}