# Workflow to demo installing a package and executing on a self-hosted runner

name: file tree

on:
  workflow_dispatch:

jobs:
  file-tree:
    runs-on: self-hosted

    steps:
      - name: Install tree
        run: |
          apt update
          apt install -y tree

      - name: Execute tree
        run: |
          time tree | tee filetreelist.txt
      
      - name: Show OS Info
        run: |
          umame -a
          cat /etc/os-release || echo "No os-release file found"
    
      - name: Check if tree exists
        run: which tree || echo "tree not found"
    
      - name: Debug OS
        run: |
          if command -v lsb_release > /dev/null; then
            lsb_release -a
          else
            echo "lsb_release not found"
          fi
