# Workflow to demo installing a package and executing on a self-hosted runner

name: file tree

on:
  workflow_dispatch:

jobs:
  file-tree:
    runs-on: self-hosted

    steps:
      - name: Download and install tree locally
        run: |
          mkdir -p ~/.local/bin
          curl -LO http://mama.indstate.edu/users/ice/tree/src/tree-1.8.0.tgz
          tar -xzf tree-1.8.0.tgz
          cd tree-1.8.0
          make
          cp tree ~/.local/bin/
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Execute tree
        run: |
          ~/.local/bin/tree | tee filetreelist.txt

