name: sidemo

on:
  push:
    branches: [ "main" ]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - env:
          DATA_VALUE: ${{ github.event.head_commit.message }}
        run: echo $DATA_VALUE